# Generated by Django 6.0.6 on 2026-06-19 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue?')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Recebido')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro')], max_length=20, null=True, verbose_name='Forma de Pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Granja_ki_frango.cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Granja_ki_frango.produto', verbose_name='Produto')),
            ],
        ),
    ]
